### GET todas las notas
GET http://localhost:3000/api/notes

###

### Crear nota
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "title": "Primera nota de prueba",
  "type": "note",
  "content": "Contenido de prueba",
  "color": "#ffffff"
}

### Registrar usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "miguel@test.com",
  "password": "123456"
}